version: '3'
services:
  cloudflared:
    image: cloudflare/cloudflared:${CLOUDFLARED_VERSION:-latest}
    container_name: cloudflared
    restart: unless-stopped
    env_file: cloudflare.env
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - ${NETWORK_NAME:-proxy}

networks:
  ${NETWORK_NAME:-proxy}:
    external: true
