version: '3'
services:
  odoo:
    image: odoo:${ODOO_VERSION}
    container_name: odoo
    env_file: odoo.env
    depends_on:
      - db
    volumes:
      - odoo_data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./custom-addons:/mnt/extra-addons
    environment:
      - HOST=${ODOO_DB_HOST}
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    # ports:
    #   - "${ODOO_PORT}:8069"    
    networks:
      - ${NETWORK_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.odoo.entrypoints=http"
      - "traefik.http.routers.odoo.rule=Host(`odoo.${DOMAIN_NAME}`)"
      - "traefik.http.routers.odoo.middlewares=odoo-https-redirect"
      - "traefik.http.middlewares.odoo-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.odoo-secure.entrypoints=https"
      - "traefik.http.routers.odoo-secure.rule=Host(`odoo.${DOMAIN_NAME}`)"
      - "traefik.http.routers.odoo-secure.tls=true"
      - "traefik.http.routers.odoo-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.odoo-secure.service=odoo"
      - "traefik.http.services.odoo.loadbalancer.server.port=${ODOO_PORT}"
      - "traefik.docker.network=proxy"
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ${NETWORK_NAME}

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - ${NETWORK_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.entrypoints=http"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.${DOMAIN_NAME}`)"
      - "traefik.http.routers.pgadmin.middlewares=pgadmin-https-redirect"
      - "traefik.http.middlewares.pgadmin-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.pgadmin-secure.entrypoints=https"
      - "traefik.http.routers.pgadmin-secure.rule=Host(`pgadmin.${DOMAIN_NAME}`)"
      - "traefik.http.routers.pgadmin-secure.tls=true"
      - "traefik.http.routers.pgadmin-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.pgadmin-secure.service=pgadmin"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    depends_on:
      - db

networks:
  ${NETWORK_NAME}:
    external: true

volumes:
  odoo_data:
  postgres_data:
  pgadmin_data:
