version: "3"
services:
  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION:-latest}
    container_name: portainer
    restart: always
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      PORTAINER_PORT: ${PORTAINER_PORT}
    env_file: portainer.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN_NAME}`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=${PORTAINER_PORT}"

volumes:
  portainer_data:


networks:
  proxy:
    external: true
