version: '3'
services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:${NPM_VERSION:-latest}'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    env_file: nginx-proxy.env
    ports:
      - '${NPM_HTTP_PORT:-80}:80'
      - '${NPM_HTTPS_PORT:-443}:443'
      - '${NPM_ADMIN_PORT:-81}:81'
    volumes:
      - npm_data:/data
      - letsencrypt:/etc/letsencrypt
    networks:
      - ${NETWORK_NAME:-proxy}
    environment:
      DB_MYSQL_HOST: ${DB_MYSQL_HOST:-db}
      DB_MYSQL_PORT: ${DB_MYSQL_PORT:-3306}
      DB_MYSQL_USER: ${DB_MYSQL_USER:-npm}
      DB_MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD:-npm}
      DB_MYSQL_NAME: ${DB_MYSQL_NAME:-npm}
    depends_on:
      - db

  db:
    image: 'mariadb:${MARIADB_VERSION:-latest}'
    container_name: npm-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-npm}
      MYSQL_DATABASE: ${DB_MYSQL_NAME:-npm}
      MYSQL_USER: ${DB_MYSQL_USER:-npm}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD:-npm}
    volumes:
      - npm_mysql:/var/lib/mysql
    networks:
      - ${NETWORK_NAME:-proxy}

volumes:
  npm_data:
  npm_mysql:
  letsencrypt:


networks:
  ${NETWORK_NAME:-proxy}:
    external: true
